#!/usr/bin/bash

# Create the private key and certificte
openssl genrsa -out tls.key 2048
openssl req -new -x509 -key tls.key -out tls.cert -days 360 -subj /CN=kubia.example.com

# Create secret from the two files
kubectl create secret tls tls-ingress --cert=tls.cert --key=tls.key
