;; Data-Directed Programming

;;
;; Complex Number Arithmetic Table:
;;
;;      | Polar      | Rectangular      | More Representation ...
;; -----+------------+------------------+------------------------
;; real | real-polar | real-rectangular | ...
;; imag | imag-polar | imag-rectangular | ...
;;
;; When new representation of complex number introduced, registering
;; their {real,imag} operations to the table by itself.
