# -----------------------------------------
#             Tank War Makefile
#
# Copyright (c) Zhou Peng <lockrecv@qq.com>
# -----------------------------------------

CC = gcc
CFLAGS = -Wall -g

export CC CFLAGS

all:
	$(MAKE) -C server clean srv.out
	$(MAKE) -C client clean cli.out
