#!/bin/bash

#
# An easy transport utility implemented by `nc` and `pipe`
#

cat <<EOF
#
# server.host: listen on port 9999
#
nc -l -p 9999

#
# client.host: create named pipe
#
mkfifo /tmp/myfifo

#
# client.host: read pipe and write to server.host
#
nc server.host 9999 < /tmp/myfifo

#
# client.host: write to pipe will be read by server.host
#
echo https://gnu.org     > /tmp/myfifo
echo https://kernel.org  > /tmp/myfifo
echo https://iobuf.org   > /tmp/myfifo

EOF
