#!/bin/bash

echo using here document to display

cat <<!CAT_HERE_DOCUMENT!
hello
this is a here
document
!CAT_HERE_DOCUMENT!

echo using here document to automate editing

echo That is line 1 >> ed_here_document.txt
echo That is line 2 >> ed_here_document.txt
echo That is line 3 >> ed_here_document.txt
echo That is line 4 >> ed_here_document.txt
cat ed_here_document.txt

ed ed_here_document.txt <<!ED_HERE_DOCUMENT!
3
d
.,\$s/is/was/
w
q
!ED_HERE_DOCUMENT!

cat ed_here_document.txt
rm -rf ed_here_document.txt

exit 0
