# ----------------------------------------------
# Copyright (C) Zhou Peng <p@ctriple.cn>
# ----------------------------------------------

objs += popt_options.o

all: $(objs)

popt_options.o: popt_options.cc
	$(CC) $(ccflags) $(include) -c $< -o $@
