# ----------------------------------------------
# Copyright (C) Zhou Peng <lockrecv@gmail.com>
# ----------------------------------------------

objs += locate_images.o

all: $(objs)

locate_images.o: locate_images.cpp
	$(CC) $(ccflags) $(include) -c $< -o $@
