#+TITLE: 简历
#+AUTHOR: 周朋
#+EMAIL: p@ctriple.cn
#+OPTIONS: toc:nil timestamp:nil num:nil creator:nil

* 基本信息

- 姓名: [[https://www.gravatar.com/avatar/f256857c773f65e111bdff3861a91344][周朋]]
- 年龄: 28
- 婚姻: 已婚
- 电话: +8615008287847
- 邮箱: p@ctriple.cn

* 英语能力

- CET-6
- 技术类英文文档阅读良好

* 编程技能

- 擅长: Linux, C, Golang, Git
- 熟练: Spark, Elasticsearch, Docker, Shell
- 了解: Java, JavaScript, HTML/CSS

* 教育情况

- 重庆邮电大学(2008 - 2012)
- 本科, 计算机科学与技术专业

* 工作经历

- 多点网络(成都)科技有限公司
- 大数据分析
- 2017年05月至今 | 成都


- 华为成都研究所
- 软件工程师A (15级)
- 2012年07月-2017年4月(5 years) | 成都

** 销量预测大数据分析

*** 简介

分析历史销售数据，分析季度、节假日、天气等因素对销售的影响，预测未来销售情况，结
果用于补货，制定促销档期选品决策。

*** 技能

Spark, Golang, Elasticsearch, Redis, Docker

** RESTful接口测试

*** 简介

工具云平台采用业界新型微服务架构,微服务间服务基于REST协议,基于开源工具
pyresttest,在此基础上加入了用例组织和管理,Swagger接口描述用例模板自动生成,集成CI
自动用例执行和用例结果展示和推送.微服务测试体系分析,工具云平台微服务测试工具选型
调研和方案制定,带领合作方实现.

*** 技能

Python, REST

** C++ OSGi测试

*** 简介

无线新业务平台架构参考Java OSGi规范,实现了一个C++兼容框架,OSGi框架相对与传统分层
架构,组件是以Bundle为单位发布和开发,各业务Bundle通过插拔方式使能.我们提供了一个
OSGi架构软件的IT测试方案,提供了一个主控Bundle负责用例Bundle管理和控制,和一个测试
Bundle,提供测试框架GTest/GMock支持.负责主控Bundle实现,参考了业界C语言OSGi框架实
现Apache Celix,移植了Celix控制台实现到C++版本.新增了用例管理和执行控制.

*** 技能

Java OSGi, C, Linux网络程序开发

** 无线需求排序系统

*** 简介

无线OSS产品试点产品级敏捷,在需求录入到交付全流程中,实现对需求的评审,分级等.需求
排序系统作为整个流程需求过滤和筛选,对下游需求起到分类,分级,过滤,排序等处理,下发
给下游各系统.需求排序系统架构和实现,选定需求排序系统实现方案
Django+Apache+Mysql.突破浏览器表格排序操作(拖动,序号,颜色,编辑, ...)等关键技术,
带领2个华为方和1个合作方,完成整个系统的开发和交付使用.

*** 技能

Python, Django Web, Apache, MySQL, JavaScript(SlickGrid)

** APS系统性能解决方案

*** 简介

APS是一款无线自研的ARM,X86 Linux平台下性能解决工具,用户通过程序运行过程中调用栈
CallGraph和每个函数CPU占用率,结合业务具体情况优化代码,达到性能目标.APS工具分为上
板采样程序,结果解析程序和结果呈现IDE三部分,我主要负责结果解析程序的开发和指导合
作方开发结果呈现IDE.结果解析程序需要完成性能采样二进制数据结合程序可执行文件和动
态链接库等ELF文件,运用GNU BFD库,统计计算出CPU,进程,线程唯独函数CPU占用率,需要处
理跨平台解析(采样数据来自Linux,解析程序在Windows上工作),ELF文件虚拟地址转函数名
等核心技术问题.IDE方面,指导合作方同事完成界面呈现设计,以及CallGraph调用绘图等关
键技术.

*** 技能

Linux内核模块, 进程地址空间, ELF文件, Dot画图, Cygwin程序开发

** 代码静态检查Molint

*** 简介

Molint是一款无线自研的C/C++代码静态检查工具,基于开源编译器Clang接口开发;作为对当
前无线商用静态检查工具PC-Lint不足的补充,实现了诸如锁配对,数组下标越界,不同类型转
换,产品编码规范遵从性等检查规则,是无线静态检查防护网不可或缺的利器.
1）方案和实现: Molint整体方案的设计,实现Molint工作流程控制核心代码,率先尝试使用
Python语言作为流程胶合代码,在Molint跨平台移植,版本级使用到桌面级使用上,都发挥了
很大作用.
2）需求和交付: 负责Molint所有需求的交流和过滤,识别出工具能否完成实现用户期
望看护场景,引导用户选择其他可替代这种方案.完成工具端到端交付到成果确认.
3）领导和合作: Molint开发过程中,负责带领5个合作方同事,澄清用户需求,评审实现方
案,check合作方同事的交付质量.

*** 技能

Linux, C++, Python, 编译器

* 自我评价

- 敢于接受陌生领域新的挑战
- 做事最求卓越,对结果负责
- 合作沟通能力强

* 兴趣爱好

- 云计算和大数据相关
- 开源和Linux相关技术
- C语言和算法相关

* 获奖荣誉

- 无线网络2016年9月编程大赛32
- 成都研究所2016年8月编程大赛9
- 成都研究所2014年7月编程大赛第2名
- 无线网络2014年9月编程大赛第4名

* 我的作品

** [[https://github.com/tabesc/esc/tree/master/works/reporter][reporter]]: Linux程序性能剖析
** [[https://github.com/tabesc/esc/tree/master/works/sysstat][sysstat]]: Linux内存,线程,中断性能数据采集
** [[https://github.com/tabesc/esc/tree/master/works/libkiss][kiss]]: Linux工具集迷你C库
** [[https://github.com/tabesc/esc/tree/master/works/less/SUMMARY.md][less]]: Unix KISS哲学思想示例
** [[https://github.com/tabesc/esc/tree/master/works/tank][tank]]: 坦克大战游戏简化版
