#!/bin/bash

go_next() {
    echo -n "next>"
    read gonext
}

cat grep_help.txt

go_next
cat RE.txt

go_next
grep wonderfull words.txt

go_next
grep -c --color wonderfull words.txt words2.txt

go_next
grep -c -v --color wonderfull words.txt words2.txt

go_next
grep --color wonderfull$ words2.txt

go_next
grep --color a[[:blank:]] words2.txt

go_next
grep --color Th.[[:space:]] words2.txt

go_next
grep -E --color [a-z]\{15\} words2.txt
