#!/bin/bash

echo "find file who newer than /bin/ls in current directory"
find . -newer /bin/ls -type f -print

echo "find file who newer than /bin/ls or name starts with .git"
find . \( -name ".git*" -or -newer /bin/ls \) -type f -print

echo "find file then execute your command on it without confirm"
find . -newer /bin/ls -type f -exec ls -l {} \;

echo "find file then execute your command on it with confirm"
find . -newer /bin/ls -type f -ok ls -l {} \;
